apiVersion: v1
kind: Secret
metadata:
  name: grafana-secret
  namespace: jenkins-metrics
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/component: visualization
    app.kubernetes.io/part-of: jenkins-metrics-collector
type: Opaque
stringData:
  # Cambiar estos valores en producción
  GF_SECURITY_ADMIN_USER: admin
  GF_SECURITY_ADMIN_PASSWORD: admin123



