apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: jenkins-metrics
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: jenkins-metrics-collector
type: Opaque
stringData:
  # Cambiar estos valores en producción
  POSTGRES_USER: jenkins_metrics
  POSTGRES_PASSWORD: jenkins_metrics_password
  POSTGRES_DB: jenkins_metrics



