apiVersion: v1
kind: ConfigMap
metadata:
  name: exporter-config
  namespace: jenkins-metrics
  labels:
    app.kubernetes.io/name: metrics-exporter
    app.kubernetes.io/component: exporter
    app.kubernetes.io/part-of: jenkins-metrics-collector
data:
  POLL_INTERVAL: "60"
  POSTGRES_HOST: "postgres-service"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "jenkins_metrics"



