apiVersion: v1
kind: Secret
metadata:
  name: jira-secrets
  namespace: jenkins-metrics
type: Opaque
data:
  # Base64 encoded values
  jira_user: dXNlckBleGFtcGxlLmNvbQ== # user@example.com
  jira_token: eW91ci1tokenLWhlcmU= # your-token-here
