apiVersion: v1
kind: Secret
metadata:
  name: jenkins-secret
  namespace: jenkins-metrics
  labels:
    app.kubernetes.io/name: metrics-exporter
    app.kubernetes.io/component: exporter
    app.kubernetes.io/part-of: jenkins-metrics-collector
type: Opaque
stringData:
  # Configurar con los datos de tu Jenkins
  JENKINS_URL: "http://tu-servidor-jenkins:8080"
  JENKINS_USER: "admin"
  JENKINS_TOKEN: "tu-api-token-aqui"



