apiVersion: 1
datasources:
  - name: Jenkins Metrics
    type: postgres
    access: proxy
    url: postgres:5432
    database: jenkins_metrics
    user: ${POSTGRES_USER}
    secureJsonData:
      password: ${POSTGRES_PASSWORD}
    jsonData:
      sslmode: 'disable'
      postgresVersion: 15
      timescaledb: false

  - name: SonarQube Metrics
    type: postgres
    access: proxy
    url: postgres:5432
    database: sonarqube_metrics
    user: ${POSTGRES_USER}
    secureJsonData:
      password: ${POSTGRES_PASSWORD}
    jsonData:
      sslmode: 'disable'
      postgresVersion: 15
      timescaledb: false

  - name: Jira Metrics
    type: postgres
    access: proxy
    url: postgres:5432
    database: jira_metrics
    user: ${POSTGRES_USER}
    secureJsonData:
      password: ${POSTGRES_PASSWORD}
    jsonData:
      sslmode: 'disable'
      postgresVersion: 15
      timescaledb: false

  - name: ArgoCD Metrics
    type: postgres
    access: proxy
    url: postgres:5432
    database: argocd_metrics
    user: ${POSTGRES_USER}
    secureJsonData:
      password: ${POSTGRES_PASSWORD}
    jsonData:
      sslmode: 'disable'
      postgresVersion: 15
      timescaledb: false

  - name: Mission Control
    type: postgres
    access: proxy
    url: postgres:5432
    database: metrics_main
    user: ${POSTGRES_USER}
    secureJsonData:
      password: ${POSTGRES_PASSWORD}
    jsonData:
      sslmode: 'disable'
      postgresVersion: 15
      timescaledb: false

  - name: Argo Rollouts Metrics
    type: postgres
    access: proxy
    url: postgres:5432
    database: argorollouts_metrics
    user: ${POSTGRES_USER}
    secureJsonData:
      password: ${POSTGRES_PASSWORD}
    jsonData:
      sslmode: 'disable'
      postgresVersion: 15
      timescaledb: false

  - name: Git Metrics
    type: postgres
    access: proxy
    url: postgres:5432
    database: git_metrics
    user: ${POSTGRES_USER}
    secureJsonData:
      password: ${POSTGRES_PASSWORD}
    jsonData:
      sslmode: 'disable'
      postgresVersion: 15
      timescaledb: false
